name: flutter_i18n
description: i18n made easy for Flutter. With flutter_i18n you can make your app international, using just a simple .json, .xml, .yaml or .toml file!
version: 0.36.0
homepage: https://github.com/ilteoood/flutter_i18n
issue_tracker: https://github.com/ilteoood/flutter_i18n/issues

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intl: '>=0.17.0-0 <=0.19.0'
  yaml: ^3.1.2
  xml2json: ^6.2.2
  path: ^1.8.3
  toml: ^0.15.0
  logging: ^1.2.0
  http: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

environment:
  sdk: '>=2.12.0 <4.0.0'
