name: Flutter drive Android
on: push
jobs:
  drive_android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [21, 29, 31]
        target: [default]
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: Run Flutter Driver basic tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          script: yes | flutter doctor --android-licenses \
            && cd example \
            && flutter drive -d emulator-5554 --driver=test_driver/main_app.dart --target=integration-test/basic_example_test.dart \
            && flutter drive -d emulator-5554 --driver=test_driver/main_app.dart --target=integration-test/network_example_test.dart \
            && flutter drive -d emulator-5554 --driver=test_driver/main_app.dart --target=integration-test/namespace_example_test.dart